journal_directory: "~/.personal_system/journal_entries"
editor_command: "code -w"

ai:
  model: "gemini-1.5-flash-latest"
  api_key_env_var: "GOOGLE_API_KEY"
  reflection_prompt: "Please reflect on this entry:
{journal_entry}"

google_auth:
  client_id: ""
  client_secret: ""
  redirect_uris:
    - "http://localhost:3000/oauth2callback"
  token_path: "~/.config/personal-journal-cli/google-tokens.json"

